#!/bin/sh
command -v git-lfs >/dev/null 2>&1 || { echo >&2 "\n'git-lfs' was not found on your path. Install Git LFS first.\n"; exit 2; }
command -v pwsh >/dev/null 2>&1 || { echo >&2 "\n'pwsh' was not found on your path. Install PowerShell first.\n"; exit 2; }

git lfs post-checkout "$@"

pwsh ProjectTools/GitHooks/DeleteEmptyFolders.ps1 -UnityProjectPath "ProjectUnity/"
